export const mentorProfiles = [
  {
    id: 1,
    name: 'Alex Chua',
    gender: 'Male',
    year: 'Year 2',
    faculty: 'College of Design and Engineering',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    id: 2,
    name: 'Sarah Tan',
    gender: 'Female',
    year: 'Year 3',
    faculty: 'Faculty of Arts & Social Sciences',
    avatar: 'https://randomuser.me/api/portraits/women/45.jpg',
  },
  {
    id: 3,
    name: 'Jason Lee',
    gender: 'Male',
    year: 'Year 1',
    faculty: 'School of Computing',
    avatar: 'https://randomuser.me/api/portraits/men/56.jpg',
  },
  {
    id: 4,
    name: 'Emily Ng',
    gender: 'Female',
    year: 'Year 4',
    faculty: 'NUS Business School',
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
  },
  {
    id: 5,
    name: 'Aisha Rahman',
    gender: 'Female',
    year: 'Year 2',
    faculty: 'Faculty of Science',
    avatar: 'https://randomuser.me/api/portraits/women/72.jpg',
  },
  {
    id: 6,
    name: 'John Tan',
    gender: 'Male',
    year: 'Year 3',
    faculty: 'Yong Loo Lin School of Medicine',
    avatar: 'https://randomuser.me/api/portraits/men/81.jpg',
  },
]